# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "cpu_profile"
edition.workspace = true
rust-version.workspace = true

[dependencies]
hvdef.workspace = true
safe_intrinsics.workspace = true

serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
sha2.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = ["Win32_Foundation", "Win32_System_Registry"]

[dev-dependencies]
test_with_tracing.workspace = true

[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
