# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "virt"
edition.workspace = true
rust-version.workspace = true

[dependencies]
aarch64defs.workspace = true
cpu_profile.workspace = true
hvdef.workspace = true
pci_core.workspace = true
memory_range = { workspace = true, features = ["inspect"] }
vm_topology = { workspace = true, features = ["inspect"] }
guestmem.workspace = true
vmcore.workspace = true
x86defs.workspace = true

inspect = { workspace = true, features = ["std"] }
mesh_protobuf.workspace = true
pal_event.workspace = true
tracelimit.workspace = true

anyhow.workspace = true
parking_lot.workspace = true
slab.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
safe_intrinsics.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_System_SystemInformation",
    "Win32_System_WindowsProgramming",
] }

[dev-dependencies]
test_with_tracing.workspace = true

[build-dependencies]
build_rs_guest_arch.workspace = true

[lints]
workspace = true
